import { useState, useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import Password from '../components/Password';
import Wipeout from '../components/Wipeout';

export default function Home() {
  const [wipeout, setWipeout] = useState(false);
  const router = useRouter();

  useEffect(() => {
    if (wipeout) {
      const timer = setTimeout(() => {
        router.push(`https://www.google.com/`);
      }, 2000);

      return () => {
        clearTimeout(timer);
      };
    }
  }, [wipeout]);

  return (
    <div className={styles.container}>
      <Head>
        <title>MIB</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.stars}></div>
      <Header />
      <Password wipeout={wipeout} setWipeout={setWipeout} />
      <Wipeout wipeout={wipeout} />
    </div>
  );
}
